# TODO add usefull package properties
[package]
name = "kaylang"
version = "0.4.2"
edition = "2021"

[lints.clippy]
needless_return = "allow"

[lints.rust]
private_bounds = "forbid"
private_interfaces = "forbid"
