[package]
name = "kaylang"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace.lints.clippy]
needless_return = "allow"

[workspace.lints.rust]
private_bounds = "deny"
private_interfaces = "deny"

[lints]
workspace = true
