# array_width = 100 # using the default
# attr_fn_like_width = 100 # using the default
# binop_separator = "Front" # unstable
# blank_lines_lower_bound = 0 # unstable
# blank_lines_upper_bound = 1 # unstable
# brace_style = "SameLineWhere" # unstable
# chain_width = 100 # using the default
# color = "Auto" # unstable
# combine_control_expr = true # unstable
# comment_width = 80 # unstable
# condense_wildcard_suffixes = false # unstable
# control_brace_style = "AlwaysSameLine" # unstable
disable_all_formatting = false
# doc_comment_code_block_width = 100 # unstable
edition = "2021"
# empty_item_single_line = true # unstable
# enum_discrim_align_threshold = 0 # unstable
# error_on_line_overflow = false # unstable
# error_on_unformatted = false # unstable
# fn_args_layout = "Tall" # deprecated
# fn_call_width = 100 # using the default
fn_params_layout = "Tall"
# fn_single_line = false # unstable
force_explicit_abi = true
# force_multiline_blocks = false # unstable
# format_code_in_doc_comments = false # unstable
# format_generated_files = true # unstable
# format_macro_bodies = true # unstable
# format_macro_matchers = false # unstable
# format_strings = false # unstable
# generated_marker_line_search_limit = 5 # unstable
# group_imports = "Preserve" # unstable
hard_tabs = false
# hex_literal_case = "Preserve" # unstable
# hide_parse_errors = false # unstable
# ignore = [ ] # unstable
# imports_granularity = "Preserve" # unstable
# imports_indent = "Block" # unstable
# imports_layout = "Mixed" # unstable
# indent_style = "Block" # unstable
# inline_attribute_width = 0 # unstable
# match_arm_blocks = true # unstable
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
merge_derives = true
# merge_imports = true # wrong type # unstable
# normalize_comments = false # unstable
# normalize_doc_attributes = false # unstable
# overflow_delimited_expr = false # unstable
remove_nested_parens = true
# reorder_impl_items = false # unstable
reorder_imports = true
reorder_modules = true
# required_version = "CARGO_PKG_VERSION" # unstable
short_array_element_width_threshold = 20
# show_parse_errors = true # unstable
# single_line_if_else_max_width = 100 # using the default
# single_line_let_else_max_width = 100 # using the default
# skip_children = false # unstable
# skip_macro_invocations = [ ] # unstable
# space_after_colon = true # unstable
# space_before_colon = false # unstable
# spaces_around_ranges = false # unstable
# struct_field_align_threshold = 0 # unstable
# struct_lit_single_line = true # unstable
# struct_lit_width = 100 # using the default
# struct_variant_width = 100 # using the default
# style_edition = "2021" # unknown
tab_spaces = 4
# trailing_comma = "Vertical" # unstable
# trailing_semicolon = true # unstable
# type_punctuation_density = "Wide" # unstable
# unstable_features = false # unstable
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
# version = "One" # unstable
# where_single_line = false # unstable
# wrap_comments = false # unstable
newline_style = "Native"
