ASCII_valid_character = ? U+0032..U+0126 ?;
UTF-8_character = ? U+0080.. ?;

(* comments *)
line_comment  = "#",  [{ASCII_valid_character | UTF-8_character}], "\n";
block_comment = "#*", [{ASCII_valid_character | UTF-8_character | "\n" | block_comment}], "*#";

(* booleans *)
boolean_literal = "true" | "false";

(* integers *)
decimal_digit     = "0".."9";
binary_digit      = "0".."1";
octal_digit       = "0".."7";
hexadecimal_digit = "0".."9" | "A".."F" | "a".."f";

decimal_integer_literal        = decimal_digit, [{decimal_digit     | "_"}];
decimal_prefix_integer_literal = "0d",          [{decimal_digit     | "_"}];
binary_integer_literal         = "0b",          [{binary_digit      | "_"}];
octal_integer_literal          = "0o",          [{octal_digit       | "_"}];
hexadecimal_integer_literal    = "0x",          [{hexadecimal_digit | "_"}];
integer_literal =
    decimal_integer_literal
    | decimal_prefix_integer_literal
    | binary_integer_literal
    | octal_integer_literal
    | hexadecimal_integer_literal
    ;

(* characters *)
character_escapes =
    "\\"
    | "\'"
    | '\"'
    | "\e"
    | "\n"
    | "\r"
    | "\t"
    | "\0"
    | ("\^", ("@" | "A".."Z" | "[" | "\" | "]" | "^" | "_" | "?"))
    ;
character_literal = "'", (ASCII_valid_character | character_escapes), "'";

(* strings *)
string_escapes = character_escapes;
string_literal = '"', [{ASCII_valid_character | string_escapes}], '"';

(* raw strings *)
raw_string_escapes = '\"';
raw_string_literal = 'r"', [{ASCII_valid_character | raw_string_escapes}], '"';

(* identifiers *)
identifier_regular = ("_" | "A".."Z" | "a".."z"), [{"_" | "A".."Z" | "a".."z" | decimal_digit}];
identifier_str     = "`", [{ASCII_valid_character}], "`";
identifier         = identifier_regular | identifier_str;

(* operators *)
operator_equals              = "=";
operator_len                 = "len";
operator_not                 = "!";
operator_not_equals          = "!=";
operator_pow                 = "**"  | "**\"  | "**|";
operator_pow_equals          = "**=" | "**\=" | "**|=";
operator_times               = "*"   | "*\"   | "*|";
operator_times_equals        = "*="  | "*\="  | "*|=";
operator_divide              = "/"   | "/\"   | "/|";
operator_divide_equals       = "/="  | "/\="  | "/|=";
operator_remainder           = "%";
operator_remainder_equals    = "%=";
operator_plus                = "+"   | "+\"   | "+|";
operator_plus_equals         = "+="  | "+\="  | "+|=";
operator_minus               = "-"   | "-\"   | "-|";
operator_minus_equals        = "-="  | "-\="  | "-|=";
operator_left_shift          = "<<"  | "<<\"  | "<<|";
operator_left_shift_equals   = "<<=" | "<<\=" | "<<|=";
operator_right_shift         = ">>";
operator_right_shift_equals  = ">>=";
operator_left_rotate         = "<<<";
operator_left_rotate_equals  = "<<<=";
operator_right_rotate        = ">>>";
operator_right_rotate_equals = ">>>=";
operator_bit_and             = "&";
operator_bit_and_equals      = "&=";
operator_bit_xor             = "^";
operator_bit_xor_equals      = "^=";
operator_bit_or              = "|";
operator_bit_or_equals       = "|=";
operator_and                 = "&&";
operator_and_equals          = "&&=";
operator_or                  = "||";
operator_or_equals           = "||=";
operator_compare             = "<=>";
operator_equals_equals       = "==";
operator_not_equals_equals   = "!==";
operator_greater             = ">";
operator_greater_or_equals   = ">=";
operator_less                = "<";
operator_less_or_equals      = "<=";

operator_prefix =
    operator_len
    | operator_not
    | operator_plus
    | operator_minus
    ;
operator_multiplicative =
    operator_times
    | operator_divide
    | operator_remainder
    ;
operator_additive =
    operator_plus
    | operator_minus
    ;
operator_shift =
    operator_left_shift
    | operator_right_shift
    | operator_left_rotate
    | operator_right_rotate
    ;
operator_comparison =
    operator_compare
    | operator_equals_equals
    | operator_not_equals_equals
    | operator_greater
    | operator_greater_or_equals
    | operator_less
    | operator_less_or_equals
    ;

operator_prefix_assignment =
    operator_not_equals
    | operator_plus_equals
    | operator_minus_equals
    ;
operator_binary_assignment =
    operator_equals
    | operator_not_equals
    | operator_pow_equals
    | operator_times_equals
    | operator_divide_equals
    | operator_remainder_equals
    | operator_plus_equals
    | operator_minus_equals
    | operator_left_shift_equals
    | operator_right_shift_equals
    | operator_left_rotate_equals
    | operator_right_rotate_equals
    | operator_bit_and_equals
    | operator_bit_xor_equals
    | operator_bit_or_equals
    | operator_and_equals
    | operator_or_equals
    ;

(* expressions *)
array_literal          = "[", [{expression, ";"}], [expression], "]";
parenthesis_expression = "(", expression, ")";
prefix_expression      = operator_prefix, primary_expression;
index_expression       = expression, "[", expression, "]";
primary_expression =
    boolean_literal
    | integer_literal
    | character_literal
    | string_literal
    | raw_string_literal
    | identifier
    | array_literal
    | parenthesis_expression
    | prefix_expression
    | index_expression
    ;

exponentiative_expression = primary_expression, [operator_pow, primary_expression];
multiplicative_expression = boolean_literal, [operator_multiplicative, boolean_literal];
additive_expression       = multiplicative_expression, [operator_additive, multiplicative_expression];
shift_expression          = additive_expression, [operator_shift, additive_expression];
bit_and_expression        = shift_expression, [operator_bit_and, shift_expression];
bit_xor_expression        = bit_and_expression, [operator_bit_xor, bit_and_expression];
bit_or_expression         = bit_xor_expression, [operator_bit_or, bit_xor_expression];
comparison_expression     = bit_or_expression, [operator_comparison, bit_or_expression];
and_expression            = comparison_expression, [operator_and, comparison_expression];
or_expression             = and_expression, [operator_or, and_expression];
expression                = or_expression;

(* statements *)
type = identifier, ["[", expression, "]"];
variable_declaration       = ("let" | "var"), identifier, [":", type], "=", expression, ";";
variable_binary_assignment = expression, operator_binary_assignment, expression, ";";
variable_prefix_assignment = operator_prefix_assignment, expression, ";";
variable_assignment        = variable_binary_assignment | variable_prefix_assignment;

break_statement    = "break", ";";
continue_statement = "continue", ";";

print    = "print", expression, ";";
eprint   = "eprint", expression, ";";
println  = "println", [expression], ";";
eprintln = "eprintln", [expression], ";";

if =
    "if", expression, scope,
    [{"else", "if", expression, scope}],
    ["else", scope]
    ;
loop  = ["do"], "loop", expression, scope_in_loop;

statement         = expression | print | variable_declaration | variable_assignment | if | loop;
statement_in_loop = statement | break_statement | continue_statement;
scope             = "{", [{line_comment | block_comment | statement | scope}], "}";
scope_in_loop     = "{", [{line_comment | block_comment | statement_in_loop | scope_in_loop}], "}";
