(* program *)
program = {line_comment | ([print | print_char], expression, ';')};

(* keywords *)
print = "print";
print_char = "print_char";

(* comments *)
line_comment = "#", ? any character ?, "\n";

(* numbers *)
zero = "0";
non_zero = "1".."9";
digit = zero | non_zero;
number = {digit};

(* symbols *)
open_round_bracket = "(";
close_round_bracket = ")";

(* operators *)
plus = "+";
minus = "-";
times = "*";
power = "^";
divide = "/";

(* expressions, from highest precedence to lowest *)
factor = number | (open_round_bracket, expression, close_round_bracket);
exponentiation = factor, [power, factor];
term = exponentiation, [times | divide, exponentiation];
expression = term, [plus | minus, term];