(* program *)
program = {line_comment | ([print], factor, ';')};

(* keywords *)
print = "print";

(* comments *)
line_comment = "#", ? any character ?, "\n";

(* numbers *)
zero = "0";
non_zero = "1".."9";
digit = zero | non_zero;
number = {digit};

(* operators *)
plus = "+";
minus = "-";
times = "*";
power = "^";
divide = "/";
unary_op = plus | minus;
binary_op = unary_op | times | power | divide;
op = unary_op | binary_op;

(* expressions *)
term_op = plus | minus;
term = number, [term_op, number];

factor_op = times | divide | power;
factor = term, [factor_op, term];